test:
	true

install:
	install -d						$(DESTDIR)/etc
	install -d						$(DESTDIR)/etc/nginx
	install -d						$(DESTDIR)/etc/nginx/conf.d
	install -m644	$(CURDIR)/conf/logformat.conf		$(DESTDIR)/etc/nginx/conf.d/

